# Generated by Django 4.0.4 on 2022-05-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_admin_user_is_verified_user_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.CharField(max_length=100),
        ),
    ]
