# Generated by Django 4.0.4 on 2022-05-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.CharField(max_length=100),
        ),
    ]
