# Generated by Django 4.0.4 on 2022-05-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
