# Generated by Django 4.0.4 on 2022-05-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_date_time_event_date_event_time'),
    ]

    operations = [
   
    ]
