# Generated by Django 4.0.4 on 2022-05-15 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_alter_event_date_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='denied',
            field=models.ManyToManyField(related_name='denied_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='pending',
            field=models.ManyToManyField(related_name='pending_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(related_name='user_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
