# Generated by Django 4.0.4 on 2022-05-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_denied_event_pending_alter_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isPrivate',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
