# Generated by Django 4.0.4 on 2022-05-15 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0005_alter_friends_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='denied',
            field=models.ManyToManyField(related_name='denied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friends',
            name='pending',
            field=models.ManyToManyField(related_name='pending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friends',
            name='friends',
            field=models.ManyToManyField(related_name='approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
